package vista;

import static javax.swing.JOptionPane.showMessageDialog;
import controlador.Controlador;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by poo2 on 25/05/2016.
 */
public class Menu extends JFrame implements ActionListener {
  private JButton lineasButton;
  private JButton autobusesButton;
  private JButton salirButton;
  private JPanel menu;
  private Controlador contrl;

  public static void main(String[] args) {
    Menu menu = new Menu("Menu");
  }

  public Menu(String titulo) {
    super(titulo);

    setContentPane(menu);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setLocationRelativeTo(null);
    setVisible(true);

    contrl = new Controlador();

    salirButton.addActionListener(this);
    lineasButton.addActionListener(new AccionLineaNueva());
    autobusesButton.addActionListener(new AccionNuevoAutobus());
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    menu = new JPanel();
    menu.setLayout(new GridBagLayout());
    lineasButton = new JButton();
    lineasButton.setText("Lineas");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menu.add(lineasButton, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menu.add(spacer1, gbc);
    autobusesButton = new JButton();
    autobusesButton.setText("Autobuses");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menu.add(autobusesButton, gbc);
    salirButton = new JButton();
    salirButton.setText("Salir");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menu.add(salirButton, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return menu;
  }
  private class AccionNuevoAutobus implements ActionListener {

    @Override
    public void actionPerformed(ActionEvent e) {
      new Autobus("Nuevo Autobus", contrl);
    }
  }

  private class AccionLineaNueva implements ActionListener {

    @Override
    public void actionPerformed(ActionEvent e) {
      new Linea("Linea nueva", contrl);
    }
  }

  @Override
  public void actionPerformed(ActionEvent e) {
    dispose();
  }


}
